#!/usr/bin/env python3
from pathlib import Path
import shutil

ROOT = Path(__file__).resolve().parents[1]
FRAMEWORK = ROOT / "micropy-system" / "src"
APP = ROOT / "app"
DEVICE = ROOT / "device"

if not FRAMEWORK.is_dir():
    raise SystemExit("Framework source is missing; initialize the Git submodule")
if not APP.is_dir():
    raise SystemExit("Application source directory is missing: app")

shutil.rmtree(DEVICE, ignore_errors=True)
shutil.copytree(FRAMEWORK, DEVICE, ignore=shutil.ignore_patterns(
    "__pycache__", "*.pyc", "system-config.json", "version.txt", "slot_main.py"))
shutil.copy2(FRAMEWORK / "slot_main.py", DEVICE / "main.py")
slot_a = DEVICE / "apps" / "a"
slot_a.mkdir(parents=True)
for item in APP.iterdir():
    if item.name in ("version.txt", "__pycache__"):
        continue
    destination = slot_a / ("app_entry.py" if item.name == "main.py" else item.name)
    if item.is_dir():
        shutil.copytree(item, destination, dirs_exist_ok=True)
    else:
        shutil.copy2(item, destination)

config = ROOT / "system-config.json"
if config.is_file():
    shutil.copy2(config, DEVICE / "system-config.json")

(DEVICE / ".micropy-system-device-tree").write_text(
    "Generated by tools/assemble.py; safe MicroPico sync root.\n",
    encoding="utf-8",
)

print(f"Assembled device filesystem at {DEVICE}")
